apiVersion: apps/v1
kind: Deployment

metadata:
  name: rdas

spec:
  replicas: 2

  selector:
    matchLabels:
      app: rdas

  template:
    metadata:
      labels:
        app: rdas

    spec:
      containers:
        - name: rdas

          image: tabby/rdas:1.0

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080